apiVersion: v1
kind: Service
metadata:
  name: lanchonete-producao
spec:
  selector:
    app: lanchonete-producao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
